# Uncomment the next line to define a global platform for your project
platform :ios, "10.0"
workspace 'iOSSample'

target 'iOSSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

	pod 'ProjectRomeSdk', '0.13.8-master.338'

  # Pods for iOSSample

end
