#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConnectedDevices.Xamarin.Droid.Sample.Resource", IsApplication=true)]

namespace ConnectedDevices.Xamarin.Droid.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Desktop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int detail_border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Hololens = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int SurfaceHub = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Unknown = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Xbox = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int Image = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int RefreshButton = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int Text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Text1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Text2 = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int detailed_id_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int detailed_kind_text = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int detailed_launch_button = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int detailed_name_text = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int detailed_proximity_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int detailed_url_text = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RemoteSystem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RemoteSystemView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
