#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConnectedDevices.Xamarin.Droid.Sample.Resource", IsApplication=true)]

namespace ConnectedDevices.Xamarin.Droid.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int discovery_type_filter_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int system_kind_filter_array = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int uri_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Desktop = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int detail_border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Hololens = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int SurfaceHub = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Unknown = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Xbox = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int Image = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int RefreshButton = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int Text = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int Text1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int Text2 = 2131099671;
			
			// aapt resource value: 0x7f060004
			public const int device_card = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int device_name = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int device_type = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int discovery_type_filter_spinner = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int feedback_btn = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int filter_layout = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int launch_log = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int launch_uri_btn = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int launch_uri_button_layout = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int launch_uri_card = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int launch_uri_edit_text = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int launch_uri_spinner = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int open_connection_btn = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int ping_buttons_layout = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int ping_card = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int ping_layout = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int ping_value = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int send_ping_btn = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int system_kind_filter_spinner = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RemoteSystem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RemoteSystemView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
